/**
 * The city's navigation raster: where the roads are, and how high the ground is.
 *
 * `public/models/cityNav.png` is generated by `scripts/prepare-map.mjs`, one
 * pixel per 3 m of world:
 *
 *   R    255 street, 128 other paved ground (yards, forecourts, car parks), 0 not paved
 *   G,B  ground height as a big-endian u16 spanning [minY, maxY]
 *   A    255 wherever any drivable surface exists; G/B mean nothing at 0
 *
 * The two levels of R exist because the map and the traffic want different
 * answers, and one mask could only ever be right for one of them. Everything
 * paved is worth *showing* — the yards and forecourts inside the blocks are real
 * ground, and a map that left them out drew a city of bare streets with hollow
 * blocks. Only the reachable street network is worth *driving*: the rest is
 * where NPC traffic used to end up looking absurd. `isRoadAt` is the wide test
 * and keeps the meaning it always had; `isDrivableAt` is the narrow one.
 *
 * It exists because Rapier cannot answer these questions from where they are
 * asked. Any collider query — `wheelGroundObject()` included — re-enters the
 * borrowed `World` from inside the physics step and throws "recursive use of an
 * object detected which would lead to unsafe aliasing in rust", which aborts the
 * step silently. The reset handler runs in `useBeforePhysicsStep`, so it cannot
 * raycast for the road. Array indexing into a preloaded raster is O(1) and safe
 * anywhere.
 *
 * The module holds a single instance because the physics step reaches it
 * directly, outside React. Everything degrades gracefully to `null` while the
 * image is still loading.
 */
import { CITY } from '@/config/cityConfig';
import { townDriveableAt, townHeightAt, townPavedAt } from './townNav';

export interface NavRaster {
  width: number;
  height: number;
  metresPerPixel: number;
  originX: number;
  originZ: number;
  minY: number;
  ySpan: number;
  /** Raw RGBA, `width * height * 4` bytes. */
  data: Uint8ClampedArray;
}

let raster: NavRaster | null = null;

export const getNav = () => raster;

/** Load the raster once. Safe to call repeatedly; resolves to the same instance. */
export async function loadCityNav(url: string): Promise<NavRaster> {
  if (raster) return raster;

  const bitmap = await createImageBitmap(await (await fetch(url)).blob());
  // Read the dimensions BEFORE closing: `ImageBitmap.close()` releases the
  // underlying buffer and zeroes width/height, so reading them afterwards
  // yields 0 and every downstream `createImageData` throws IndexSizeError.
  const width = bitmap.width;
  const height = bitmap.height;

  const canvas = document.createElement('canvas');
  canvas.width = width;
  canvas.height = height;
  const ctx = canvas.getContext('2d', { willReadFrequently: true });
  if (!ctx) throw new Error('2D canvas context unavailable');
  ctx.drawImage(bitmap, 0, 0);
  const { data } = ctx.getImageData(0, 0, width, height);
  bitmap.close();

  raster = {
    width,
    height,
    metresPerPixel: CITY.nav.metresPerPixel,
    originX: CITY.nav.originX,
    originZ: CITY.nav.originZ,
    minY: CITY.nav.minY,
    ySpan: CITY.nav.maxY - CITY.nav.minY || 1,
    data,
  };
  return raster;
}

/** World metres -> raster pixel. Fractional; callers floor as needed. */
export const toPixelX = (n: NavRaster, x: number) => (x - n.originX) / n.metresPerPixel;
export const toPixelZ = (n: NavRaster, z: number) => (z - n.originZ) / n.metresPerPixel;
export const toWorldX = (n: NavRaster, px: number) => n.originX + px * n.metresPerPixel;
export const toWorldZ = (n: NavRaster, pz: number) => n.originZ + pz * n.metresPerPixel;

const inside = (n: NavRaster, px: number, pz: number) =>
  px >= 0 && pz >= 0 && px < n.width && pz < n.height;

/**
 * The island's own surfaces, consulted first by all three queries below.
 *
 * The baked raster covers `city.glb`; the island station's town is drawn at
 * runtime from config and is therefore not in it (`townNav` says why). Asking
 * the patch first rather than merging the two rasters keeps this file's
 * meaning intact — the PNG is still exactly what `prepare-map.mjs` wrote — and
 * costs a bounds check per query on the mainland, where the patch's box does
 * not reach.
 */

/** True where the pixel is paved at all — what the map draws. */
export function isRoadPixel(n: NavRaster, px: number, pz: number): boolean {
  if (townPavedAt(px, pz)) return true;
  if (!inside(n, px, pz)) return false;
  return n.data[(pz * n.width + px) * 4] > 127;
}

/**
 * True where the pixel is street a car may be put on or driven along.
 *
 * Narrower than `isRoadPixel` by exactly the paving that is built on, roofed or
 * cut off from the street network. Used by the traffic AI and by the reset
 * snap; anything that only *draws* the world should use the wide test.
 */
export function isDrivablePixel(n: NavRaster, px: number, pz: number): boolean {
  if (townDriveableAt(px, pz)) return true;
  if (!inside(n, px, pz)) return false;
  return n.data[(pz * n.width + px) * 4] > 191;
}

/** Ground height at a pixel, or null where no drivable surface was rasterised. */
export function heightAtPixel(n: NavRaster, px: number, pz: number): number | null {
  const town = townHeightAt(px, pz);
  if (town !== null) return town;
  if (!inside(n, px, pz)) return null;
  const i = (pz * n.width + px) * 4;
  if (n.data[i + 3] < 128) return null;
  return n.minY + ((n.data[i + 1] << 8) | n.data[i + 2]) / 65535 * n.ySpan;
}

/** True if the given world position is on tarmac of any kind. */
export function isRoadAt(x: number, z: number): boolean {
  const n = raster;
  if (!n) return false;
  return isRoadPixel(n, Math.floor(toPixelX(n, x)), Math.floor(toPixelZ(n, z)));
}

/** True if the given world position is street a car may drive. */
export function isDrivableAt(x: number, z: number): boolean {
  const n = raster;
  if (!n) return false;
  return isDrivablePixel(n, Math.floor(toPixelX(n, x)), Math.floor(toPixelZ(n, z)));
}

/** Ground height at a world position, or null if unknown. */
export function groundHeightAt(x: number, z: number): number | null {
  const n = raster;
  if (!n) return null;
  return heightAtPixel(n, Math.floor(toPixelX(n, x)), Math.floor(toPixelZ(n, z)));
}

/**
 * Direction of the road through a pixel, as a heading.
 *
 * Probes 18 axes and keeps the one with the longest unbroken run of tarmac
 * through the point — for a street that is the street's own axis. The axis is
 * undirected, so the returned heading is whichever of the two ends lies closer
 * to `prefer`; resetting should not spin the car around to face backwards.
 */
function roadHeadingAt(n: NavRaster, px: number, pz: number, prefer: number): number {
  const REACH = 24; // pixels, i.e. 72 m
  let bestAxis = 0;
  let bestRun = -1;

  for (let a = 0; a < 18; a++) {
    const theta = (a / 18) * Math.PI;
    const dx = Math.cos(theta);
    const dz = Math.sin(theta);
    let run = 0;
    for (const sign of [1, -1]) {
      for (let d = 1; d <= REACH; d++) {
        if (!isDrivablePixel(n, Math.round(px + dx * d * sign), Math.round(pz + dz * d * sign))) break;
        run++;
      }
    }
    if (run > bestRun) { bestRun = run; bestAxis = theta; }
  }

  // Axis (cos, sin) in pixel space is (x, z) in world space; forward is
  // (-sin h, -cos h), so h = atan2(-dx, -dz).
  const dx = Math.cos(bestAxis);
  const dz = Math.sin(bestAxis);
  const candidates = [Math.atan2(-dx, -dz), Math.atan2(dx, dz)];
  const delta = (h: number) => Math.abs(Math.atan2(Math.sin(h - prefer), Math.cos(h - prefer)));
  return delta(candidates[0]) <= delta(candidates[1]) ? candidates[0] : candidates[1];
}

export interface RoadFix {
  position: [number, number, number];
  heading: number;
  /** Metres from the query point to the road that was found. */
  distance: number;
}

/**
 * Nearest *drivable* point to a world position, with a heading along that road.
 *
 * Deliberately the narrow test: this is what puts the player back on the road
 * and what recovers a strayed NPC, and neither wants to be dropped onto a roof
 * deck or into a walled yard just because it is paved.
 *
 * Searches outward ring by ring, so the first hit is the closest and the scan
 * costs nothing when the car is already on tarmac (the common case). Returns
 * null if nothing is found inside `maxMetres`, or if the raster has not loaded.
 */
export function nearestRoad(x: number, z: number, prefer = 0, maxMetres = 600): RoadFix | null {
  const n = raster;
  if (!n) return null;

  const cx = Math.floor(toPixelX(n, x));
  const cz = Math.floor(toPixelZ(n, z));
  const maxRing = Math.ceil(maxMetres / n.metresPerPixel);

  for (let r = 0; r <= maxRing; r++) {
    let bestPx = -1, bestPz = -1, bestD2 = Infinity;

    // Walk the ring's perimeter only; interior rings were covered already.
    for (let dz = -r; dz <= r; dz++) {
      const edge = Math.abs(dz) === r;
      for (let dx = -r; dx <= r; dx += edge ? 1 : 2 * r || 1) {
        const px = cx + dx, pz = cz + dz;
        if (!isDrivablePixel(n, px, pz)) continue;
        const d2 = dx * dx + dz * dz;
        if (d2 < bestD2) { bestD2 = d2; bestPx = px; bestPz = pz; }
        if (r === 0) break;
      }
    }

    if (bestPx >= 0) {
      const wx = toWorldX(n, bestPx + 0.5);
      const wz = toWorldZ(n, bestPz + 0.5);
      const h = heightAtPixel(n, bestPx, bestPz);
      return {
        position: [wx, (h ?? 0) + 0.6, wz],
        heading: roadHeadingAt(n, bestPx, bestPz, prefer),
        distance: Math.sqrt(bestD2) * n.metresPerPixel,
      };
    }
  }

  return null;
}
